name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.publishMessage }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        run: npm ci
      - name: publish message to another job
        id: publish
        run: echo "publishMessage=hello from build message" >> $GITHUB_OUTPUT
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: output project status from another job
        run: |
          echo "${{needs.build.outputs.script-file}}"
          echo "${{needs.build.outputs.script-file}}"
          echo "${{needs.build.outputs.script-file}}"
          echo "${{needs.build.outputs.script-file}}"
          echo "${{needs.build.outputs.script-file}}"
          echo "${{needs.build.outputs.script-file}}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
